version: '2'
services:
    web:
        container_name: <<CONTAINER_NAME>>_web
        build:
            context: ./
            dockerfile: web.docker
        volumes:
            - ./:/var/www
        links:
            - app
        expose:
            - 80
        environment:
            - "VIRTUAL_HOST=<<SUBDOMAIN>>.<<DOMAIN>>"
        network_mode: "bridge"
    app:
        container_name: <<CONTAINER_NAME>>_app
        build:
            context: ./
            dockerfile: app.docker
        volumes:
            - ./:/var/www
        links:
            - database
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=database"
        network_mode: "bridge"
    database:
        container_name: <<CONTAINER_NAME>>_db
        image: mysql:<<MY_SQL_VERSION>>
        environment:
            - "MYSQL_ROOT_PASSWORD=<<MYSQL_ROOT_PASSWORD>>"
            - "MYSQL_DATABASE=<<MYSQL_DATABASE>>"
        network_mode: "bridge"
        ports:
            - "<<DBPORT>>:3306"
